Change XML test data so that xmlns are correctly set
Fix errors like :
======================================================================
ERROR: test_georss_box_latlong (tests.test_reconstitute.ReconstituteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/tests/test_reconstitute.py", line 43, in <lambda>
    func = lambda self, name=root: self.eval(name)
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/tests/test_reconstitute.py", line 26, in eval
    results = feedparser.parse(data)
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/planet/vendor/feedparser.py", line 4001, in parse
    saxparser.parse(source)
  File "/usr/lib/python2.7/dist-packages/drv_libxml2.py", line 208, in parse
    eltName,eltQName,attributesNSImpl)
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/planet/vendor/feedparser.py", line 1801, in startElementNS
    raise UndeclaredNamespace, "'%s' is not associated with a namespace" % givenprefix
UndeclaredNamespace: 'georss' is not associated with a namespace