Fix test_missing_item_pubDate no longer passing
Fixes :
======================================================================
FAIL: test_missing_item_pubDate (tests.test_reconstitute.ReconstituteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/tests/test_reconstitute.py", line 43, in <lambda>
    func = lambda self, name=root: self.eval(name)
  File "/home/olivier/svn/svn.debian.org/python-apps/planet-venus/git-svn/planet-venus/tests/test_reconstitute.py", line 38, in eval
    self.assertEqual(eval(rhs), eval(lhs, results.entries[0]))
AssertionError: (2006, 6, 21, 13, 16, 41, 2, 172, 0) != time.struct_time(tm_year=2014, tm_mon=1, tm_mday=27, tm_hour=17, tm_min=16, tm_sec=24, tm_wday=0, tm_yday=27, tm_isdst=0)

----------------------------------------------------------------------